name: CI on Commit

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup nuget
      uses: Nuget/Setup-nuget@v1.0.2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore nuget packages
      run: nuget restore "Hunter Industries API.sln"

    - name: Build solution
      run: |
        msbuild.exe "Hunter Industries API.sln" /p:configuration="Release"
