name: CI on Commit

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: msbuild & "Hunter Industries API.sln" /p:Configuration=Release
