name: CI on Commit

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: |
        nuget restore "Hunter Industries API.sln"
        dotnet restore "Hunter Industries API Control Panel/Hunter Industries API Control Panel.csproj"

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create build directory
      run: mkdir _build

    - name: Build solution
      run: |
        msbuild.exe "Hunter Industries API.sln" /p:configuration="Release"
