name: CI on Commit

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create build directory
      run: mkdir _build

    - name: Build solution
      run: |
        msbuild.exe "Hunter Industries API.sln" /p:configuration="Release"
