name: CI on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Install VS Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.WebBuildTools --includeRecommended --includeOptional"

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create build directory
      run: mkdir _build

    - name: Build solution
      run: |
        msbuild.exe "Hunter Industries API.sln" /p:configuration="Release"

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
