name: CI on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Build solution
      run: |
        MSBuild.exe "Hunter Industries API.sln" /p:configuration="Release"

    - name: Run tests
      run: vstest.console.exe ".\tests\Hunter Industries API.Tests\bin\Release\Hunter Industries API.Tests.dll"
